data:
  data_keys: ['sh', 'nj', 'nc']
  sh:
    dataset_path: ../data/handled/sh/sh_4505_1488.npy
    adjacency_matrix_path: ../data/handled/sh/sh_spatial_24.npy
    time_step: 1488
    node_num: 4505
  nj:
    dataset_path: ../data/handled/nj/nj_8000_2784.npy
    adjacency_matrix_path: ../data/handled/nj/nj_spatial_24.npy
    time_step: 2784
    node_num: 8000
  nc:
    dataset_path: ../data/handled/nc/nc_7702_336.npy
    adjacency_matrix_path: ../data/handled/nc/nc_spatial_24.npy
    time_step: 336
    node_num: 7702

task:
  his_num: 12
  pred_num: 1
  batch_size: 64 
  test_batch_size: 83 
  task_num: 2

model:
  node_feature_dim: 2
  edge_feature_dim: 4
  message_dim: 1
  hidden_dim: 16
  output_dim: 1
  meta_dim: 16
  num_layers: 1  
  depth: 1      
  num_heads: 1  
  d_model: 16 
  mlp_dim: 32   
  update_lr: 0.001  
  meta_lr: 0.001   
  loss_lambda: 1.5
  update_step: 1
  update_step_test: 10
  tp: True
  sp: True
  dropout: 0.2 
  drop_path: 0.1 